name: Regression Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  regression-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest
          pip install pytest-cov
          pip install python-dotenv

      - name: Run regression tests
        run: |
          pytest tests/regression